package com.example.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * Soundbox palette — teal/cyan core with slightly richer containers for a more distinctive identity.
 * Keeps full Material 3 role coverage for dynamic color and accessibility.
 */

// Light
val md_theme_light_primary = Color(0xFF006B84)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB8ECFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F28)
val md_theme_light_secondary = Color(0xFF4A626A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7F0)
val md_theme_light_onSecondaryContainer = Color(0xFF051E25)
val md_theme_light_tertiary = Color(0xFF565D7E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF131937)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FAFC)
val md_theme_light_onBackground = Color(0xFF161D1F)
val md_theme_light_surface = Color(0xFFF5FAFC)
val md_theme_light_onSurface = Color(0xFF161D1F)
val md_theme_light_surfaceVariant = Color(0xFFD9E4E8)
val md_theme_light_onSurfaceVariant = Color(0xFF3E484C)
val md_theme_light_outline = Color(0xFF6E787C)
val md_theme_light_outlineVariant = Color(0xFFBDC8CC)
val md_theme_light_inverseOnSurface = Color(0xFFECF1F4)
val md_theme_light_inverseSurface = Color(0xFF2B3133)
val md_theme_light_inversePrimary = Color(0xFF5CD5F7)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006B84)
val md_theme_light_scrim = Color(0xFF000000)

// Dark
val md_theme_dark_primary = Color(0xFF5CD5F7)
val md_theme_dark_onPrimary = Color(0xFF003642)
val md_theme_dark_primaryContainer = Color(0xFF004E60)
val md_theme_dark_onPrimaryContainer = Color(0xFFB8ECFF)
val md_theme_dark_secondary = Color(0xFFB1CBD4)
val md_theme_dark_onSecondary = Color(0xFF1C343B)
val md_theme_dark_secondaryContainer = Color(0xFF334A52)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7F0)
val md_theme_dark_tertiary = Color(0xFFBFC4EB)
val md_theme_dark_onTertiary = Color(0xFF282E4D)
val md_theme_dark_tertiaryContainer = Color(0xFF3F4465)
val md_theme_dark_onTertiaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0C1214)
val md_theme_dark_onBackground = Color(0xFFDEE3E6)
val md_theme_dark_surface = Color(0xFF0C1214)
val md_theme_dark_onSurface = Color(0xFFDEE3E6)
val md_theme_dark_surfaceVariant = Color(0xFF3E484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDC8CC)
val md_theme_dark_outline = Color(0xFF879296)
val md_theme_dark_outlineVariant = Color(0xFF3E484C)
val md_theme_dark_inverseOnSurface = Color(0xFF0C1214)
val md_theme_dark_inverseSurface = Color(0xFFDEE3E6)
val md_theme_dark_inversePrimary = Color(0xFF006B84)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5CD5F7)
val md_theme_dark_scrim = Color(0xFF000000)
