package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Poweramp Signature Theme Palette - Obsidian, Metallic Slate, Neon Cyan, Electric Amber
val Poweramp_Obsidian_Dark = Color(0xFF080B10)
val Poweramp_Surface_Dark = Color(0xFF10141D)
val Poweramp_Card_Dark = Color(0xFF161D2A)
val Poweramp_Card_Elevated = Color(0xFF1F293A)
val Poweramp_Bevel_Light = Color(0xFF2E3D52)
val Poweramp_Bevel_Dark = Color(0xFF070A0F)

// Poweramp Neon Lighting
val Poweramp_Cyan = Color(0xFF00E5FF)
val Poweramp_Cyan_Glow = Color(0x6600E5FF)
val Poweramp_Amber = Color(0xFFFF9100)
val Poweramp_Amber_Glow = Color(0x66FF9100)
val Poweramp_Lime = Color(0xFF00E676)
val Poweramp_Purple = Color(0xFFD500F9)

val Poweramp_Text_Primary = Color(0xFFF0F4F8)
val Poweramp_Text_Secondary = Color(0xFF8E9EB5)
val Poweramp_Text_Tertiary = Color(0xFF5A687D)
val Poweramp_Knob_Cap = Color(0xFF1B2230)
val Poweramp_Knob_Rim = Color(0xFF2C384C)

// Material Theme Mappings
val md_theme_light_primary = Color(0xFF00838F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB2EBF2)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = Color(0xFF4C626A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE6F0)
val md_theme_light_onSecondaryContainer = Color(0xFF061E26)
val md_theme_light_tertiary = Color(0xFFFF9100)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE0B2)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF4F7FA)
val md_theme_light_onBackground = Color(0xFF14181F)
val md_theme_light_surface = Color(0xFFF4F7FA)
val md_theme_light_onSurface = Color(0xFF14181F)
val md_theme_light_surfaceVariant = Color(0xFFDCE2E9)
val md_theme_light_onSurfaceVariant = Color(0xFF424B54)
val md_theme_light_outline = Color(0xFF727C88)
val md_theme_light_outlineVariant = Color(0xFFC0CAD5)
val md_theme_light_inverseOnSurface = Color(0xFFEEF2F6)
val md_theme_light_inverseSurface = Color(0xFF2B323D)
val md_theme_light_inversePrimary = Color(0xFF00E5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00838F)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF00E5FF)
val md_theme_dark_onPrimary = Color(0xFF001F24)
val md_theme_dark_primaryContainer = Color(0xFF004D56)
val md_theme_dark_onPrimaryContainer = Color(0xFF80F2FF)
val md_theme_dark_secondary = Color(0xFFFF9100)
val md_theme_dark_onSecondary = Color(0xFF4D2700)
val md_theme_dark_secondaryContainer = Color(0xFF6E3900)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD199)
val md_theme_dark_tertiary = Color(0xFF00E676)
val md_theme_dark_onTertiary = Color(0xFF003918)
val md_theme_dark_tertiaryContainer = Color(0xFF005324)
val md_theme_dark_onTertiaryContainer = Color(0xFF7CFFB0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF080B10)
val md_theme_dark_onBackground = Color(0xFFF0F4F8)
val md_theme_dark_surface = Color(0xFF080B10)
val md_theme_dark_onSurface = Color(0xFFF0F4F8)
val md_theme_dark_surfaceVariant = Color(0xFF161D2A)
val md_theme_dark_onSurfaceVariant = Color(0xFF8E9EB5)
val md_theme_dark_outline = Color(0xFF38475C)
val md_theme_dark_outlineVariant = Color(0xFF1F293A)
val md_theme_dark_inverseOnSurface = Color(0xFF080B10)
val md_theme_dark_inverseSurface = Color(0xFFF0F4F8)
val md_theme_dark_inversePrimary = Color(0xFF00838F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF00E5FF)
val md_theme_dark_scrim = Color(0xFF000000)


